### ISSUE TITLE
Please correct the warning text to indicate "Enabled" instead of "Available" in f5-agility-labs-cert/docs/class8/module04/lab3.rst 

### ISSUE THREAD

**Issue by danielcayer** [f5devcentral/f5-agility-labs-cert#30]
I believe the intention of the "Warning" shown towards the bottom of f5-agility-labs-cert/docs/class8/module04/lab3.rst is to make sure the virtual server is "Enabled" before continuing (the previous section called for disabling the virtual server). The status of the www_pool should remain "Unavailable", because the "mysql" monitor is still in use and failing for all pool members, and the next section is to text overriding the "inherit from pool" default behaviour...
The way it's written currently, this Warning lead me to think I had to restore the original http monitor in the www_pool's configuration.

I recommend changing the sentence:
"Make sure all virtual servers, pools and pool members are Available before continuing."
like this:
"Make sure all virtual servers, pools and pool members are Enabled before continuing."

**Comment by 6a6d** [comment]
Fixed!
